Use uia2 backend by default if platform version is greater or equal to 6
appium/appium pull request #10073
Opened 2018-01-25 11:45 UTC by mykola-mokhnach

## Proposed changes

Use uia2 backend by default if platform version is greater or equal to 6

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Further comments

We had to do this a while ago. UIObject is considered as obsolete and is not supported anymore by Google since Android 6 (or even 5).

2018-01-25 19:42 UTC, imurchie reviewed
While in theory I'm ok with this. it would necessitate publishing Appium 2.0, since it is a breaking change.

At this point I would suggest just logging the fact that the results might be inconsistent, telling them to set the `automationName`, and allowing them to go on their merry way.

2018-01-25 20:15 UTC, jlipps reviewed
i agree with isaac, i think we can't push this now but should log a warning to the user instead saying they're using a deprecated driver

2018-01-25 20:24 UTC, mykola-mokhnach commented
Ok, lets put a warning message instead

2018-01-25 21:04 UTC, dpgraham approved these changes

2018-01-29 15:24 UTC, mykola-mokhnach commented
@imurchie are you ok with these changes?

2018-01-29 15:50 UTC, imurchie requested changes

2018-01-29 15:50 UTC, imurchie commented on lib/appium.js
> +                 `${this.validAutomations.UIAUTOMATOR2.toLowerCase()} ` +
The name should be in quotes.

2018-01-29 15:50 UTC, imurchie commented on lib/appium.js
> +                 "on Android >= 6, since UIAutomation1 framework " +
UIAutomator

2018-01-29 15:50 UTC, imurchie commented on lib/appium.js
> +                 `using ${this.validAutomations.XCUITEST.toLowerCase()} ` +
Quotes around name.

2018-01-29 15:52 UTC, mykola-mokhnach commented on lib/appium.js
> +                 "on Android >= 6, since UIAutomation1 framework " +
fixed

2018-01-29 15:52 UTC, mykola-mokhnach commented on lib/appium.js
> +                 `${this.validAutomations.UIAUTOMATOR2.toLowerCase()} ` +
added quotes

2018-01-29 15:52 UTC, mykola-mokhnach commented on lib/appium.js
> +                 `using ${this.validAutomations.XCUITEST.toLowerCase()} ` +
added quotes

2018-01-29 16:14 UTC, imurchie approved these changes

2018-01-29 16:14 UTC, merged