Update move examples
appium/appium pull request #10445
Opened 2018-03-30 05:23 UTC by wswebcreation

I've been struggling the last days with the `move` command because the `moveTo` implies an absolute position, but it's just a relative offset, see also https://github.com/appium/appium/issues/6257#issuecomment-196949576

This PR hopefully makes it more clear

2018-03-30 05:27 UTC, jeaye commented
This should save people a lot of time. Thank you, @wswebcreation!

2018-03-30 05:27 UTC, jeaye requested changes

2018-03-30 05:27 UTC, jeaye commented on docs/en/commands/interactions/touch/move.md
> +// Move to // Move to 0,0 (as in, an additional -100 in each direction)
We've a double comment here.

2018-03-30 08:57 UTC, wswebcreation commented on docs/en/commands/interactions/touch/move.md
> +// Move to // Move to 0,0 (as in, an additional -100 in each direction)
Fixed it

2018-03-30 10:29 UTC, tfcardoso commented
@wswebcreation you sure? I was under the impression that behavior had been changed by @mykola-mokhnach in https://github.com/appium/appium-android-driver/pull/292

2018-03-30 10:37 UTC, mykola-mokhnach commented
Yes the moveTo coordinates should be absolute according to the spec. However, previous appium version had a bug, where these coordinates were considered as relative.

2018-03-30 10:42 UTC, wswebcreation commented
Ok, so if I understand correctly this will be fixed in 1.8.0?

Meaning that this PR is only for the versions < 1.8.0

Maybe we should still tell something about it in the docs, I've seen a lot of questions in the webdriver.io channel concerning this part

2018-03-30 16:34 UTC, jeaye approved these changes

2018-04-06 17:14 UTC, dpgraham commented
Sorry for the late review on this one.

This .md file is actually auto-generated and the actual file that needs to be edited is: https://github.com/appium/appium/blob/master/commands-yml/commands/interactions/touch/move.yml

@wswebcreation Do you want to transfer your changes over to the .yml file or do you want me to do that?

2018-04-07 09:24 UTC, wswebcreation commented
Hi @dpgraham

I’d like to but is this still valid. Because when I look at the remark of @mykola-mokhnach I do wonder.

2018-04-10 18:10 UTC, jlipps commented
@dpgraham we should put a big invisible comment at the top of these files that they are auto-generated and shouldn't be edited by hand.

2018-04-11 15:02 UTC, dpgraham commented
@jlipps Yeah, that's a good idea

2018-05-23 15:51 UTC, closed without merging