fixed broken path of sample app path
appium/appium pull request #10500
Opened 2018-04-08 20:03 UTC by saikrishna321

## Proposed changes

Sample application path was broken. 

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x ] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla.js.foundation/appium/appium)
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

2018-04-08 23:30 UTC, jlipps requested changes

2018-04-08 23:30 UTC, jlipps commented on sample-code/javascript-wd/test/helpers/apps.js
> +  exports.iosTestApp = path.resolve(__dirname, "..", "../..", "apps", "TestApp.app.zip");
these should be separated as `"..", ".."`

2018-05-23 12:45 UTC, saikrishna321 commented
@jlipps ping

2018-05-23 12:54 UTC, imurchie commented
The failing test has been fixed. This branch just needs to be rebased with master.

2018-06-08 17:21 UTC, closed without merging