Fix incorrect page source Python example
appium/appium pull request #10871
Opened 2018-06-13 15:04 UTC by mjtimblin

## Proposed changes

In the Python implementation of page source, `self.driver_page_source` is an object; not a method. Therefore, the `()` do not belong. When the `()` is included, the following error occurs:
`TypeError: 'unicode' object is not callable.`

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla.js.foundation/appium/appium)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

## Further comments

N/A

2018-06-18 19:44 UTC, jlipps approved these changes

2018-06-18 19:45 UTC, jlipps requested changes
whoops, sorry @mjtimblin but it looks like this is the file that can't be edited directly. See the line at the top of the file for instructions on where to make the changes.

2018-06-22 05:29 UTC, mjtimblin commented
Sorry about that, @jlipps. All fixed!

2018-06-22 16:54 UTC, dpgraham approved these changes

2018-06-22 16:54 UTC, merged

2018-06-22 16:55 UTC, dpgraham commented
Thanks @mjtimblin

2018-06-22 17:10 UTC, dpgraham commented
@jlipps Maybe we should add a link on the top right corner of all the pages that that links users to the GitHub page.