Update capability, command, tvos doc
appium/appium pull request #12597
Opened 2019-05-07 02:19 UTC by KazuCocoa

## Proposed changes

- Make open-notification false for espresso since it is not available so far
    - https://github.com/appium/appium-espresso-driver/issues/440
- Add `buildToolsVersion` in the capability
- Append tvOS documentation
    - e.g. JS examples

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the [CLA](https://cla.js.foundation/appium/appium)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2019-05-08 09:23 UTC, Madh93 requested changes
Great job! I think `python` code requires these changes :+1:

2019-05-08 09:28 UTC, KazuCocoa commented on docs/en/writing-running-appium/ios/ios-tvos.md
> +execute_script('mobile: pressButton', { 'name': 'Up' })
ah. Exactly, thanks!

2019-05-16 03:06 UTC, jlipps commented on docs/en/writing-running-appium/caps.md
> +|`buildToolsVersion`| Specify the Android `build-tools` version to be something different than the default, which is to use the most recent version. It is helpful to use particular version while your
`It is helpful to use a non-default version if your environment uses alpha/beta build tools`

2019-05-16 03:06 UTC, jlipps commented on docs/en/writing-running-appium/ios/ios-tvos.md
> +tvOS does actions on the _focused_ element. You can get the value of the `focus` attribute via [Attributes API](http://appium.io/docs/en/commands/element/attributes/attribute/). _Get active element_
`tvOS performs actions`

2019-05-16 03:06 UTC, jlipps commented on docs/en/writing-running-appium/ios/ios-tvos.md
> +_pressButton_ and get focused element by _get active element_ are basic actions in tvOS.
pressButton and getting the focused element by get active element are the basic actions for tvOS

2019-05-16 03:06 UTC, jlipps commented on docs/en/writing-running-appium/ios/ios-tvos.md
> +Consider adding `wait` methods since tvOS also has animation.
Consider using

2019-05-16 04:09 UTC, jlipps approved these changes

2019-05-16 04:54 UTC, merged