Km/add settings in caps
appium/appium pull request #12776
Opened 2019-06-14 15:36 UTC by KazuCocoa

## Proposed changes

Related to https://github.com/appium/appium/pull/12440
We can guide users to follow this if they would like to set settings like https://github.com/appium/appium/issues/12771

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla.js.foundation/appium/appium)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2019-06-18 13:29 UTC, dpgraham requested changes

2019-06-18 13:29 UTC, dpgraham commented on docs/en/writing-running-appium/caps.md
> +|`settings[theNameOfSettingsAPI]`| Update [Settings API](https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/settings.md) in a session creation step. |e.g., `'settings[mjpegScaling
* `settings[settingsKey]`
* `Update [Appium Settings]`
* `in a session creation step` to `on session creation`.

2019-06-18 13:39 UTC, dpgraham approved these changes

2019-06-18 13:40 UTC, merged

2019-06-19 03:40 UTC, jlipps reviewed
nice, i forgot we could do this :-)