docs: add migrations for arguments
appium/appium pull request #16052
Opened 2021-11-08 20:26 UTC by boneskull

This depends on #15938.

This list is certainly incomplete and just downright wrong, so I'm hoping others can help.

When the `--help` text says "iOS only" or "Android only", I am not sure which drivers those entail.  

(If it's multiple, it makes me wonder if a "base iOS" or "base Android" driver might make sense)

2021-11-08 20:27 UTC, boneskull commented on docs/en/advanced-concepts/migrating-to-appium-2.0.md
> +| Old Argument                 | New Argument                                                                                       | Driver(s)                      |
should sort this table when it's complete

2021-11-08 21:26 UTC, jlipps commented
@boneskull I think probably 80-85% of the args which were in 1.x but which are not in 2.x have not been moved to driver args. Instead they were deprecated and have been removed. I think it's probably better to find the PRs which added driver args to the different drivers, and mention those in terms of the migration. All the others should be listed as no longer available (instead the way to set them on the command line if desired is to make them part of `--default-capabilities`).

2021-11-08 21:27 UTC, jlipps commented
https://github.com/appium/appium-uiautomator2-driver/pull/459/files (this one is still open, so probably is superseded by your work now?)

2021-11-08 21:27 UTC, jlipps commented
for xcuitest: https://github.com/appium/appium-xcuitest-driver/pull/1331

2021-11-08 21:27 UTC, boneskull commented
got it

2021-11-08 21:29 UTC, jlipps commented
> (If it's multiple, it makes me wonder if a "base iOS" or "base Android" driver might make sense)

The current situation is that both the XCUITest driver and the UiAutomator2 driver extend other drivers (IOSDriver and AndroidDriver), which are no longer used directly themselves. It has been proposed that those projects should be removed and instead the shared code extracted into IOSBaseDriver and AndroidBaseDriver. It's a good idea and would form the basis of the (also planned) iOS and Android monorepos, which we decided we didn't need to address concretely until after Appium 2.0 was out.

2021-11-09 06:51 UTC, mykola-mokhnach commented
> The current situation is that both the XCUITest driver and the UiAutomator2 driver extend other drivers (IOSDriver and AndroidDriver)

Not really. XCUITest driver does not depend on any legacy stuff anymore.

2021-11-09 06:55 UTC, mykola-mokhnach commented on docs/en/advanced-concepts/migrating-to-appium-2.0.md
> +#### CLI Argument Migrations
I'd say all these almost all args should be removed from v2 as they are:
- driver-specific
- could be replaced with default capabilities
It only makes sense to keep these, that a system admin would potentially like to keep, in order to override user-provided capabilities on the server side, for which we could have potentially have another common argument. Something like `enforceCapabilities`. Capabilities provided there would have priority over all other values included these provided by users

2021-11-09 16:47 UTC, jlipps commented
> Not really. XCUITest driver does not depend on any legacy stuff anymore.

Oh cool. I missed that it didn't depend on `appium-ios-driver` anymore. Good stuff!

2022-04-04 22:28 UTC, jlipps requested changes
i think we should keep only the args i commented 'keep' on. the others are all better accessed as driver specific capabilities.

2022-04-04 22:28 UTC, jlipps commented on docs/en/advanced-concepts/migrating-to-appium-2.0.md
> +| `--webdriveragent-port`      | `--driver-xcuitest-webdriveragent-port`                                                            | `xcuitest`                     |
keep

2022-04-04 22:28 UTC, jlipps commented on docs/en/advanced-concepts/migrating-to-appium-2.0.md
> +| `--webkit-debug-proxy-port`  | `--driver-xcuitest-webkit-debug-proxy-port`                                                        | `xcuitest`                     |
keep

2022-04-04 22:28 UTC, jlipps commented on docs/en/advanced-concepts/migrating-to-appium-2.0.md
> +| `--suppress-adb-kill-server` | `--driver-uiautomator2-adb-kill-server`                                                            | `uiautomator2`                 |
keep

2022-04-04 22:28 UTC, jlipps commented on docs/en/advanced-concepts/migrating-to-appium-2.0.md
> +| `--chromedriver-executable`  | `--driver-uiautomator2-chromedriver-executable` _or_ `--driver-selendroid-chromedriver-executable` | `uiautomator2` or `selendroid` |
keep (only `uiautomator2`, selendroid is gone)

2022-04-04 22:28 UTC, jlipps commented on docs/en/advanced-concepts/migrating-to-appium-2.0.md
> +| `--bootstrap-port`           | `--driver-uiautomator2-bootstrap-port`                                                             | `uiautomator2`                 |
keep

2023-11-25 18:56 UTC, closed without merging