fix filename
appium/appium pull request #19608
Opened 2024-01-04 09:19 UTC by phoet

## Proposed changes

The file extension was .py should be .rb for the ruby example.

It took me some time to actually find where to change this. Would be great to have a deeplink into the underlying documentation to help first time contributors like me.

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the CLA
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2024-01-04 17:21 UTC, eglitise requested changes
Thanks for the fix! Could you please also sign the CLA?

> Would be great to have a deeplink into the underlying documentation to help first time contributors like me.

There is a button in the top right of every documentation page for this exact purpose :)

2024-01-04 17:21 UTC, eglitise commented on packages/appium/docs/en/quickstart/test-rb.md
> +```python title="test.rb"
Could you also change the `python` at the start of this line to `ruby`?

2024-01-04 18:35 UTC, phoet commented on packages/appium/docs/en/quickstart/test-rb.md
> +bundle add appium_lib
adding this via bundler, otherwise there is nothing you can do with `bundle exec` later on

2024-01-04 18:36 UTC, phoet commented on packages/appium/docs/en/quickstart/test-rb.md
> -bundle install
the installation is done when adding already.

2024-01-04 18:37 UTC, phoet commented
> There is a button in the top right of every documentation page for this exact purpose :)

true dat. i kinda expected it next to the `2 weeks ago` icon at the bottom.

2024-01-04 19:05 UTC, KazuCocoa commented
Could you sign the CLA?


Not for this pr:

We should give links to https://github.com/appium/appium/tree/master/packages/appium/sample-code/quickstarts/ in each quickstart documentation so that readers can refer to the exact code for the example code. Some code like this Ruby's bundle install and bundle exec ruby test.rb expected to be called in the quickstarts.

I'll tweak the relevant documentation later.

2024-01-04 19:14 UTC, phoet commented
i signed the CLA

2024-01-04 22:32 UTC, jlipps commented
/easycla

2024-01-05 08:46 UTC, KazuCocoa commented
hm, perhaps signed email address and git commented email address were different

2024-01-05 17:15 UTC, KazuCocoa approved these changes

2024-01-05 17:16 UTC, merged

2024-01-05 20:59 UTC, phoet commented
thx 😍