Add server parameter for WebDriverAgent local port
appium/appium pull request #6898
Opened 2016-09-27 00:25 UTC by domuro

## Proposed changes

Enable specifying the WebDriverAgent port as a server parameter, so multiple Appium XCUI tests can be run concurrently.

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://docs.google.com/forms/d/1lOfXRw_0VCk7gYzjj4WLetGu7yelDVo5LWh0z7pGftE/viewform)
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### Reviewers: @imurchie, @jlipps, ...

2016-09-27 00:25 UTC, triager commented
Can one of the admins verify this patch?

2016-09-27 00:28 UTC, triager commented
Can one of the admins verify this patch?

2016-09-27 14:31 UTC, imurchie commented
This is a desired capability. Why do you want it to be a server flag?

2016-09-27 18:25 UTC, yaphatak commented
@imurchie I think it will be better to have this so that people can launch a node per device with different port. This is something similar to what we have for `--chromedriver-port` or `selendroid`

2016-09-27 18:34 UTC, imurchie requested changes
Thanks for this! A couple of changes, but otherwise good.

2016-09-27 18:34 UTC, imurchie commented on lib/parser.js
> +  [['--web-driver-agent-port'], {
I would prefer `webdriveragent-port`.

2016-09-27 18:34 UTC, imurchie commented on lib/parser.js
> +    help: '(IOS-only) Local port used for communication with WebDriverAgent'
This should include info that it is XCUITest only, not just iOS only.

2016-09-28 11:23 UTC, imurchie approved these changes

2016-09-28 11:23 UTC, imurchie commented
Awesome! Thanks for this!

2016-09-28 11:23 UTC, merged