graceful handling of SIGTERM and SIGINT such that return codes are mo…
appium/appium pull request #7015
Opened 2016-10-14 05:00 UTC by montdidier

## Proposed changes

Upon receiving SIGTERM appium exits with code 143 which is line with the documentation presented [here](https://nodejs.org/api/process.html#process_signal_events). However it is not an expected result from the point of view of many existing system tools. A SIGTERM would usually result in a graceful shutdown and an exit code of 0. 

I've installed basic signal handers for SIGTERM and SIGINT that shutdown express when they are met. The code then exits gracefully with an exit code of 0.

The specific problem I encountered was met when managing appium using launchctl on OSX which I use to manage appium process life. Shutdown is performed via SIGTERM and launchctl expects an exit code of 0 as is typical. 

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [x ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x ] I have read the [CONTRIBUTING](/CONTRIBUTING.md) doc
- [x ] I have signed the [CLA](https://docs.google.com/forms/d/1lOfXRw_0VCk7gYzjj4WLetGu7yelDVo5LWh0z7pGftE/viewform)
- [x ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x ] I have added necessary documentation (if appropriate)
- [x ] Any dependent changes have been merged and published in downstream modules

## Further comments

NA

### Reviewers: @imurchie, @jlipps

2016-10-14 05:00 UTC, triager commented
Can one of the admins verify this patch?

2016-10-14 05:03 UTC, triager commented
Can one of the admins verify this patch?

2016-10-14 12:20 UTC, imurchie requested changes
Two small style changes (I need to update our eslint config to make that an error, not a warning).

But thi is great! Thank you for taking the time to improve the system!

2016-10-14 12:20 UTC, imurchie commented on lib/main.js
> +  process.on('SIGTERM', function() {
Same.

2016-10-14 17:54 UTC, jlipps requested changes

2016-10-14 17:54 UTC, jlipps commented on lib/main.js
> +    server.close();
we `await server.close()` earlier, so we should probably convert this into an async function for consistency.

2016-10-17 04:18 UTC, montdidier commented on lib/main.js
> +    server.close();
No problem will address all comments.

2016-10-17 11:51 UTC, imurchie commented
Looks good to me! Could you, as a last step, squash the two commits? Then we can get this in!

2016-10-17 11:52 UTC, imurchie approved these changes

2016-10-24 05:27 UTC, montdidier commented
squash done. anything else?

2016-10-24 11:54 UTC, imurchie commented
I'm good with this. @jlipps?

2016-10-24 22:25 UTC, jlipps approved these changes

2016-10-24 22:25 UTC, jlipps commented
LGTM now, thanks

2016-10-28 12:46 UTC, merged