Add --enable-heapdump feature
appium/appium pull request #8176
Opened 2017-04-05 21:22 UTC by mykola-mokhnach

## Proposed changes

There are memory leaks in Appium, but they are quite hard to catch. The heapdump tool allows to create node heap snapshot with one simple 'kill -SIGUSR2 &lt;NODEPID&gt;' command (works in *nix system only). This gives us a possibility to provide users with a better possibilities to debug the process and allows us to ask them to provide these dump to us if necessary for detailed investigation (and leaks fixing), since such kind of bugs is usually very hard to reproduce in dev environment.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Reviewers: @imurchie, @jlipps

2017-04-05 21:22 UTC, triager commented
Can one of the admins verify this patch?

2017-04-05 21:23 UTC, triager commented
Can one of the admins verify this patch?

2017-04-05 21:43 UTC, jlipps requested changes

2017-04-05 21:43 UTC, jlipps commented on docs/en/writing-running-appium/server-args.md
> +|`--enable-heapdump`|false|Enables NodeJS memory dumps collections feature. This feature is extremely useful for finding memory leaks. Use the 'kill -SIGUSR2 &lt;PID&gt;' command to create a dump of
s/mode/more

2017-04-05 21:43 UTC, jlipps commented on lib/main.js
> +  if (args.isHeapdumpEnabled) {
i wouldn't find this particularly unreadable to just include the 3 lines in the main function below. but i don't feel strongly about it.

2017-04-05 21:43 UTC, jlipps commented on package.json
> +    "heapdump": "0.x"
i think we try to keep this list of deps alphabetized. if it looks alphabetized, mind moving this up?

2017-04-05 21:52 UTC, mykola-mokhnach commented on docs/en/writing-running-appium/server-args.md
> +|`--enable-heapdump`|false|Enables NodeJS memory dumps collections feature. This feature is extremely useful for finding memory leaks. Use the 'kill -SIGUSR2 &lt;PID&gt;' command to create a dump of
fixed

2017-04-05 21:53 UTC, mykola-mokhnach commented on lib/main.js
> +  if (args.isHeapdumpEnabled) {
This way the code simply looks more structured as for my taste

2017-04-05 21:53 UTC, mykola-mokhnach commented on package.json
> +    "heapdump": "0.x"
fixed

2017-04-05 21:58 UTC, jlipps approved these changes

2017-04-06 13:32 UTC, imurchie requested changes
This will be a nice feature!

2017-04-06 13:32 UTC, imurchie commented on docs/en/writing-running-appium/server-args.md
> +|`--enable-heapdump`|false|Enables NodeJS memory dumps collections feature. This feature is extremely useful for finding memory leaks. Use the 'kill -SIGUSR2 &lt;PID&gt;' command to create a dump of
I'd prefer the link to the Rising Stack article be "this article" (rather than "this").

2017-04-06 13:32 UTC, imurchie commented on lib/parser.js
> +    dest: 'isHeapdumpEnabled',
The naming scheme throughout does not include "is". `heapdumpEnabled` would be more in line.

2017-04-06 13:32 UTC, imurchie commented on lib/main.js
> +    require('heapdump');
Does this not need some sort of call, somewhere, to `heapdump.writeSnapshot`? Or is requiring it somehow enough?

2017-04-06 13:38 UTC, mykola-mokhnach commented on lib/main.js
> +    require('heapdump');
This is pretty enough to be able to send SIGUSR2. writeSnapshot is only needed for Windows

2017-04-06 13:41 UTC, imurchie commented on lib/main.js
> +    require('heapdump');
Ok! Cool!

2017-04-06 13:43 UTC, mykola-mokhnach commented on docs/en/writing-running-appium/server-args.md
> +|`--enable-heapdump`|false|Enables NodeJS memory dumps collections feature. This feature is extremely useful for finding memory leaks. Use the 'kill -SIGUSR2 &lt;PID&gt;' command to create a dump of
fixed

2017-04-06 13:43 UTC, mykola-mokhnach commented on lib/parser.js
> +    dest: 'isHeapdumpEnabled',
changed

2017-04-06 13:49 UTC, imurchie approved these changes

2017-04-06 16:51 UTC, imurchie commented
This doesn't seem to be buildable on Travis. Should it be an optional dependency? Are there any restrictions on its being compiled? Do we need to futz with some flags?

2017-04-06 18:12 UTC, jlipps commented
is heapdump plat/arch dependent? we want to avoid having to build different versions of appium for different platforms is possible. maybe making it an optional dep is a good idea

2017-04-07 21:18 UTC, mykola-mokhnach commented
Made the module optional and added a bugreport to the module repository

2017-04-07 21:32 UTC, mykola-mokhnach commented
Also I'm a bit worried about the warning in the log:

```
Starting with io.js 3 and Node.js 4, building native extensions requires C++11-compatible compiler, which seems unavailable on this VM. Please read https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements.
```

Might this be a reason of module build failure?

2017-04-07 22:10 UTC, mykola-mokhnach commented
@jlipps C++ 11 compiler absence is the reason of the failure: https://github.com/bnoordhuis/node-heapdump/issues/99 

Is it possible to update the build machine?

2017-04-18 13:46 UTC, imurchie commented
@mykola-mokhnach Are you going to update the `.travis.yml` file to get the C++ compiler up to snuff here?

2017-04-18 15:42 UTC, mykola-mokhnach commented
Sorry @imurchie , but to be honest, I don't have much time and passion to play with Travis. I'd rather keep it as is or leave this task to you guys if you don't mind ;)

2017-04-18 16:06 UTC, imurchie commented
Nor do I, but it's necessary to keep things from being always broken. Alas.

2017-04-18 16:06 UTC, merged

2017-04-18 16:21 UTC, imurchie commented
https://github.com/appium/appium/pull/8273