Documentation on android test coverage using uiautomator2-driver
appium/appium pull request #8803
Opened 2017-07-07 12:15 UTC by Sw0rdstream

## Proposed changes

Add documentation for coverage collection of using uiautomator2 .
Fix issue: https://github.com/appium/appium/issues/7317

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla.js.foundation/appium/appium)
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

### Reviewers: @imurchie, @jlipps, ...

2017-07-07 17:41 UTC, jlipps requested changes
looks great overall! made some specific comments. thanks for including bilingual docs!

2017-07-07 17:41 UTC, jlipps commented on docs/en/writing-running-appium/android_coverage.md
> +* You may need a following structure of files:
`You may need the following file structure:`

2017-07-07 17:41 UTC, jlipps commented on docs/en/writing-running-appium/android_coverage.md
> +### [3] Now, build apk and run Appium tests!!
`Now, build the apk and run Appium tests!` (one exclamation point should be enough, I think! even though this is indeed a very exciting situation)

2017-07-07 17:41 UTC, jlipps commented on docs/en/writing-running-appium/android_coverage.md
> +### [4] 关于拉出HTML报告
looks like this section needs to be translated to english still

2017-07-07 17:41 UTC, jlipps commented on lib/parser.js
> +  [['--android-coverage-end-intent'], {
since this is not an existing CLI param, let's just not include it here or in the command line flag documentation. it should be a capability only.

2017-07-07 17:41 UTC, jlipps commented on docs/en/writing-running-appium/server-args.md
> +|`--android-coverage-end-intent`|false| [DEPRECATED] - A broadcast action implemented by yourself which is used to dump coverage into file system. Passed to -a in adb shell am broadcast -a |`--androi
this can be removed

2017-07-07 17:41 UTC, jlipps commented on docs/en/writing-running-appium/default-capabilities-arg.md
> +| --android-coverage-end-intent   | androidCoverageEndIntent      |
this can be removed

2017-07-07 23:09 UTC, Sw0rdstream commented
Thanks for comments. Revised.

2017-07-11 22:29 UTC, Sw0rdstream commented
@jlipps

2017-07-13 18:31 UTC, SrinivasanTarget commented
https://github.com/appium/appium/issues/7317

2017-07-20 15:49 UTC, Sw0rdstream commented
@jlipps @imurchie Excuse me, could you check my new changes?

2017-07-20 16:07 UTC, imurchie requested changes
A few formatting and language notes. Otherwise looks good to me! Thanks!

2017-07-20 16:07 UTC, imurchie commented on docs/en/writing-running-appium/android_coverage.md
> +   |____ JacocoInstrumentation.java  The instrument class created by you. Also it needs implemeting InstrumentActivitylistener.
"Also it needs to implement `InstrumentActivityListener`"

2017-07-20 16:07 UTC, imurchie commented on docs/en/writing-running-appium/android_coverage.md
> +* Configure followings in your caps
"Configure the following in your caps:"

2017-07-20 16:07 UTC, imurchie commented on docs/en/writing-running-appium/android_coverage.md
> +src/main/java/com/example/pkg
For the sake of consistency, all of the descriptions in this file structure ought to begin and end with a `*`, or none of them should. Right now it's a mixture.

2017-07-21 16:03 UTC, Sw0rdstream commented
@imurchie Thanks for your comments. Please check my new revision.

2017-07-21 16:09 UTC, imurchie requested changes
A couple of further comments. Then all good.

2017-07-21 16:09 UTC, imurchie commented on docs/en/writing-running-appium/android_coverage.md
> +   |____ MainActivity.java *Your main activity*
These items are still inconsistent. Some have an asterisk at the beginning and end of the description, some just the beginning, some not at all.

2017-07-21 16:09 UTC, imurchie commented on docs/en/writing-running-appium/android_coverage.md
> + `automationName` ： `uiautomator2` (case irrelevant)
Perhaps these should be an unordered list (as in the "Requirement" section above)?

2017-08-04 19:56 UTC, jlipps commented
hi @Sw0rdstream are you up to make the last requested changes? looks like we're close to merging!

2017-08-07 05:41 UTC, Sw0rdstream commented
was in holiday these days. I am preparing it.

2017-08-14 22:07 UTC, jlipps commented
ok great, thank you!

2017-08-20 17:02 UTC, Sw0rdstream commented
Revision submitted. Please check again. Sorry for long waiting. @jlipps @imurchie

2017-08-21 12:18 UTC, imurchie approved these changes

2017-08-21 18:10 UTC, jlipps approved these changes

2017-08-21 18:10 UTC, merged

2017-08-21 18:10 UTC, jlipps commented
Thank you for taking the time to submit these helpful docs, @Sw0rdstream!