Implemented mouse and session commands
appium/appium pull request #9354
Opened 2017-10-02 17:23 UTC by dpgraham

2017-10-03 10:20 UTC, imurchie approved these changes

2017-10-03 17:26 UTC, SrinivasanTarget requested changes
Do we have mouse interactions in Mobile? @dpgraham @imurchie @jlipps 

I think we should document endpoints only related(only that works) in our project and leave rest to Selenium to handle the doc's. Thoughts please.

2017-10-03 17:35 UTC, imurchie commented
Yeah, that makes sense.

2017-10-04 16:39 UTC, dpgraham commented
I already have done a bunch of the documentation for non-mobile endpoints.

I think we should include web/mouse interactions because it's relevant to Appium users when working within a web context and also, the Mac and Windows drivers may support these features.

2017-10-06 16:49 UTC, merged