Touch id commands
appium/appium pull request #9382
Opened 2017-10-04 18:16 UTC by dpgraham

## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](/CONTRIBUTING.md) doc
- [ ] I have signed the [CLA](https://cla.js.foundation/appium/appium)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2017-10-05 05:29 UTC, vmaxim commented on commands-yml/commands/device/simulator/toggle-touch-id-enrollment.yml
> +  url: /session/:session_id/simulator/touch_id
It should be `/session/:session_id/simulator/toggle_touch_id_enrollment`.

2017-10-05 14:40 UTC, imurchie requested changes

2017-10-05 14:40 UTC, imurchie commented on commands-yml/commands/device/simulator/toggle-touch-id-enrollment.yml
> +    This call will only work if Appium process or its parent application (e.g. Terminal.app or Appium.app) has access to Mac OS accessibility in System Preferences > Security & Privacy > Privacy > Ac
`if the Appium process`

2017-10-05 14:40 UTC, imurchie commented on commands-yml/commands/device/simulator/toggle-touch-id-enrollment.yml
> +    - name: match
Should be an optional `enabled` parameter. https://github.com/appium/appium-base-driver/blob/master/lib/mjsonwp/routes.js#L427-L429

2017-10-05 14:40 UTC, imurchie commented on commands-yml/commands/device/simulator/toggle-touch-id-enrollment.yml
> +    This call will only work if Appium process or its parent application (e.g. Terminal.app or Appium.app) has access to Mac OS accessibility in System Preferences > Security & Privacy > Privacy > Ac
[Pedantic alert] `e.g.` should be followed by a comma (i.e., `(e.g., Terminal.app or Appium.app)`)

2017-10-05 20:37 UTC, dpgraham commented
Fixes pushed

2017-10-06 04:45 UTC, SrinivasanTarget requested changes

2017-10-06 04:45 UTC, SrinivasanTarget commented on commands-yml/commands/device/simulator/toggle-touch-id-enrollment.yml
> +    uiautomation: false
Isn't it false?

2017-10-06 17:25 UTC, merged