Document broadcastIntent endpoint
appium/appium pull request #9621
Opened 2017-11-11 00:15 UTC by dpgraham

(see https://github.com/appium/appium/issues/3172)

2017-11-11 15:29 UTC, SrinivasanTarget requested changes

2017-11-11 15:29 UTC, SrinivasanTarget commented on docs/en/commands/device/activity/broadcast-intent.md
> +`GET /wd/hub/session/:session_id/device/current_activity`
`/wd/hub/session/:sessionId/appium/device/broadcast_intent`

2017-11-14 20:01 UTC, imurchie reviewed
I think much more is needed than the intent name. The various available arguments need to be looked at and decided upon (what can be used maliciously, what are needed to be handled, etc.?)

2017-11-14 20:47 UTC, dpgraham commented
```
Specification for intent arguments
For activity manager commands that take an intent argument, you can specify the intent with the following options:

Show all

-a action
Specify the intent action, such as android.intent.action.VIEW. You can declare this only once.
-d data_uri
Specify the intent data URI, such as content://contacts/people/1. You can declare this only once.
-t mime_type
Specify the intent MIME type, such as image/png. You can declare this only once.
-c category
Specify an intent category, such as android.intent.category.APP_CONTACTS.
-n component
Specify the component name with package name prefix to create an explicit intent, such as com.example.app/.ExampleActivity.
-f flags
Add flags to the intent, as supported by setFlags().
--esn extra_key
Add a null extra. This option is not supported for URI intents.
-e | --es extra_key extra_string_value
Add string data as a key-value pair.
--ez extra_key extra_boolean_value
Add boolean data as a key-value pair.
--ei extra_key extra_int_value
Add integer data as a key-value pair.
--el extra_key extra_long_value
Add long data as a key-value pair.
--ef extra_key extra_float_value
Add float data as a key-value pair.
--eu extra_key extra_uri_value
Add URI data as a key-value pair.
--ecn extra_key extra_component_name_value
Add a component name, which is converted and passed as a ComponentName object.
--eia extra_key extra_int_value[,extra_int_value...]
Add an array of integers.
--ela extra_key extra_long_value[,extra_long_value...]
Add an array of longs.
--efa extra_key extra_float_value[,extra_float_value...]
Add an array of floats.
--grant-read-uri-permission
Include the flag FLAG_GRANT_READ_URI_PERMISSION.
--grant-write-uri-permission
Include the flag FLAG_GRANT_WRITE_URI_PERMISSION.
--debug-log-resolution
Include the flag FLAG_DEBUG_LOG_RESOLUTION.
--exclude-stopped-packages
Include the flag FLAG_EXCLUDE_STOPPED_PACKAGES.
--include-stopped-packages
Include the flag FLAG_INCLUDE_STOPPED_PACKAGES.
--activity-brought-to-front
Include the flag FLAG_ACTIVITY_BROUGHT_TO_FRONT.
--activity-clear-top
Include the flag FLAG_ACTIVITY_CLEAR_TOP.
--activity-clear-when-task-reset
Include the flag FLAG_ACTIVITY_CLEAR_WHEN_TASK_RESET.
--activity-exclude-from-recents
Include the flag FLAG_ACTIVITY_EXCLUDE_FROM_RECENTS.
--activity-launched-from-history
Include the flag FLAG_ACTIVITY_LAUNCHED_FROM_HISTORY.
--activity-multiple-task
Include the flag FLAG_ACTIVITY_MULTIPLE_TASK.
--activity-no-animation
Include the flag FLAG_ACTIVITY_NO_ANIMATION.
--activity-no-history
Include the flag FLAG_ACTIVITY_NO_HISTORY.
--activity-no-user-action
Include the flag FLAG_ACTIVITY_NO_USER_ACTION.
--activity-previous-is-top
Include the flag FLAG_ACTIVITY_PREVIOUS_IS_TOP.
--activity-reorder-to-front
Include the flag FLAG_ACTIVITY_REORDER_TO_FRONT.
--activity-reset-task-if-needed
Include the flag FLAG_ACTIVITY_RESET_TASK_IF_NEEDED.
--activity-single-top
Include the flag FLAG_ACTIVITY_SINGLE_TOP.
--activity-clear-task
Include the flag FLAG_ACTIVITY_CLEAR_TASK.
--activity-task-on-home
Include the flag FLAG_ACTIVITY_TASK_ON_HOME.
--receiver-registered-only
Include the flag FLAG_RECEIVER_REGISTERED_ONLY.
--receiver-replace-pending
Include the flag FLAG_RECEIVER_REPLACE_PENDING.
--selector
Requires the use of -d and -t options to set the intent data and type.
```

2017-12-19 17:34 UTC, closed without merging